#!/usr/bin/env node
/**
 * JSON Schema → TypeScript + zod (SPEC_WEBSITE §3, multi-repo variant).
 *
 * For each agent in config/sources.json:
 *   - If public/data/<agent>/schema.json was fetched from the agent's live `data` branch
 *     (not sample data), generate src/types/generated/<agent>.ts with
 *     json-schema-to-typescript and src/lib/validators/generated/<agent>.ts with
 *     json-schema-to-zod.
 *   - Otherwise write stubs that re-export the hand-written zod contract in
 *     src/lib/schemas/, which mirrors that agent spec's §6 exactly.
 *
 * The site's pages always validate with the hand-written contract (the §6 shapes);
 * generated validators let `npm run gen:types` surface drift between an agent's
 * published schema and §6 (printed as a warning, never a build failure).
 *
 *   node scripts/gen-types.mjs [--schema-dir <dir>]   # --schema-dir: read <dir>/<agent>.schema.json instead
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';
import { jsonSchemaToZod } from 'json-schema-to-zod';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const TYPES_DIR = path.join(ROOT, 'src/types/generated');
const ZOD_DIR = path.join(ROOT, 'src/lib/validators/generated');
const argDir = process.argv.indexOf('--schema-dir');
const SCHEMA_DIR = argDir > -1 ? path.resolve(process.argv[argDir + 1]) : null;

const HAND_WRITTEN = {
  real_estate: { module: 'realEstate', schema: 'realEstateLatest', type: 'RealEstateLatest' },
  macro: { module: 'macro', schema: 'macroLatest', type: 'MacroLatest' },
  grants: { module: 'grants', schema: 'grantsLatest', type: 'GrantsLatest' },
  repo_maint: { module: 'repoMaint', schema: 'repoMaintLatest', type: 'RepoMaintLatest' },
};

const config = JSON.parse(await readFile(path.join(ROOT, 'config/sources.json'), 'utf8'));
const report = existsSync(path.join(ROOT, 'public/data/_fetch-report.json'))
  ? JSON.parse(await readFile(path.join(ROOT, 'public/data/_fetch-report.json'), 'utf8'))
  : { agents: [] };

/** Inline local `#/$defs/...` / `#/definitions/...` refs so json-schema-to-zod sees plain schemas. */
function deref(node, root, depth = 0) {
  if (depth > 40) return {};
  if (Array.isArray(node)) return node.map((n) => deref(n, root, depth));
  if (!node || typeof node !== 'object') return node;
  if (typeof node.$ref === 'string' && node.$ref.startsWith('#/')) {
    const target = node.$ref
      .slice(2)
      .split('/')
      .reduce((o, k) => (o ? o[k] : undefined), root);
    const rest = { ...node };
    delete rest.$ref;
    return deref({ ...(target ?? {}), ...rest }, root, depth + 1);
  }
  const out = {};
  for (const [k, v] of Object.entries(node)) {
    if (k === '$defs' || k === 'definitions') continue;
    out[k] = deref(v, root, depth);
  }
  return out;
}

/** Some exporters emit several roots under `definitions`, each with its own `$defs`. */
function roots(schema) {
  const defs = schema.definitions ?? {};
  const multi = Object.entries(defs).filter(
    ([, v]) => v && typeof v === 'object' && (v.$defs || v.properties),
  );
  if (!schema.properties && multi.length) return multi.map(([name, s]) => [name, s]);
  return [[schema.title ?? 'Latest', schema]];
}

const pascal = (s) =>
  s.replace(/(^|[_\-\s])(\w)/g, (_, __, c) => c.toUpperCase()).replace(/[^A-Za-z0-9]/g, '');

await mkdir(TYPES_DIR, { recursive: true });
await mkdir(ZOD_DIR, { recursive: true });

for (const agent of config.agents) {
  const hw = HAND_WRITTEN[agent.id];
  const live = report.agents.find((a) => a.id === agent.id && !a.sample);
  const schemaPath = SCHEMA_DIR
    ? path.join(SCHEMA_DIR, `${agent.id}.schema.json`)
    : path.join(ROOT, 'public/data', agent.id, 'schema.json');
  const useSchema = existsSync(schemaPath) && (SCHEMA_DIR || live);
  const banner = (src) =>
    `/* eslint-disable */\n// AUTO-GENERATED by scripts/gen-types.mjs — do not edit.\n// Source: ${src}\n\n`;

  if (!useSchema) {
    if (!hw) {
      console.warn(`[gen:types] ${agent.id}: no schema.json and no hand-written contract; skipping`);
      continue;
    }
    const src = `hand-written contract src/lib/schemas/${hw.module}.ts (SPEC §6); no live schema.json on ${agent.repo}@${agent.branch}`;
    await writeFile(
      path.join(TYPES_DIR, `${agent.id}.ts`),
      banner(src) + `export type { ${hw.type} as Latest } from '../../lib/schemas/${hw.module}';\n`,
    );
    await writeFile(
      path.join(ZOD_DIR, `${agent.id}.ts`),
      banner(src) + `export { ${hw.schema} as latestSchema } from '../../schemas/${hw.module}';\n`,
    );
    console.log(`[gen:types] ${agent.id}: hand-written contract (no live schema.json)`);
    continue;
  }

  const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
  const src = `${agent.repo}@${agent.branch}:schema.json`;
  let ts = banner(src);
  let zod = banner(src) + `import { z } from 'zod';\n\n`;
  const rs = roots(schema);
  for (const [i, [name, sub]] of rs.entries()) {
    const typeName = pascal(name);
    const standalone = { ...sub, title: typeName };
    const compiled = await compile(standalone, typeName, { bannerComment: '', additionalProperties: false });
    // Several roots can define the same helper names; give each its own namespace.
    ts += rs.length > 1 ? `export namespace ${typeName}NS {\n${compiled}}\n\n` : compiled + '\n';
    const flat = deref(sub, sub);
    const exportName =
      i === 0 && rs.length === 1 ? 'latestSchema' : `${typeName[0].toLowerCase()}${typeName.slice(1)}Schema`;
    const body = jsonSchemaToZod(flat, { module: 'none' });
    zod += `export const ${exportName} = ${body};\n\n`;
  }
  if (rs.length > 1)
    zod += `export const latestSchema = ${pascal(rs[0][0])[0].toLowerCase()}${pascal(rs[0][0]).slice(1)}Schema;\n`;
  await writeFile(path.join(TYPES_DIR, `${agent.id}.ts`), ts);
  await writeFile(path.join(ZOD_DIR, `${agent.id}.ts`), zod);
  console.log(
    `[gen:types] ${agent.id}: generated from ${path.relative(ROOT, schemaPath)} (${rs.length} root${rs.length > 1 ? 's' : ''})`,
  );

  // Drift check: does the live latest.json also satisfy the site's §6 contract?
  // fetch-data already enforced this (or fell back to fixtures), so this is informational.
}
